### ISSUE TITLE
Give direct commands rather than arrows for directory structure.

### ISSUE THREAD

**Issue by RJ722** [BlockchainDevs/MeetupDAO#19]
In the following line, IMHO it would be better if we could give direct commands, rather than indicating arrows for paths.

> Navigate through the folders as follows meetupdao --> UI/web3 --> open index.html

We may replace the above statement with:

```
# Navigate through the folders as follows:
cd MeetupDAO
cd UI/web3
# Open the web page.
open index.html
```

**Comment by amitkumarj441** [comment]
@RJ722 Thanks for pointing this out. I've assigned you this issue to fix and looking forward to your PR.
